transformer streams - deserialization error.
org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id 1
Caused by: java.net.SocketException: Unexpected end of file from server